blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/thinkgrid-labs/moment-less/discussions
    about: Ask questions and discuss usage in GitHub Discussions
